<a href="https://colab.research.google.com/github/bekdata/mohirdev_datascines/blob/main/_017%7C_arifmetik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [6]:
# series elementlar va ular bilan amallar
s1 = pd.Series([1,2,3,4], index = ['a','c','d','e'])
s1

a    1
c    2
d    3
e    4
dtype: int64

In [7]:
s2 = pd.Series([4,3,2,1], index = ['a','b','c','d'])
s2

a    4
b    3
c    2
d    1
dtype: int64

In [8]:
s1 + s2

a    5.0
b    NaN
c    4.0
d    4.0
e    NaN
dtype: float64

In [9]:
# dataframe va ular bilan birga amallar bajarish
df1 = pd.DataFrame(np.arange(9.).reshape(3,3), columns=list('bcd'), index=['Olma','Anor','Uzum'])
df2 = pd.DataFrame(np.arange(12.).reshape(4,3), columns=list('abc'), index=['Olma','Anor','Qovun','Anjir'])

In [10]:
df1 + df2

        a    b    c   d
Anjir NaN  NaN  NaN NaN
Anor  NaN  7.0  9.0 NaN
Olma  NaN  1.0  3.0 NaN
Qovun NaN  NaN  NaN NaN
Uzum  NaN  NaN  NaN NaN

In [11]:
df1-df2

        a    b    c   d
Anjir NaN  NaN  NaN NaN
Anor  NaN -1.0 -1.0 NaN
Olma  NaN -1.0 -1.0 NaN
Qovun NaN  NaN  NaN NaN
Uzum  NaN  NaN  NaN NaN

In [13]:
df2.add(df1, fill_value = 0)    # qiymat yo`q bolgan joylarni 0 bilan to`ldiradi

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   7.0   9.0  5.0
Olma   0.0   1.0   3.0  2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN   6.0   7.0  8.0

b    3.0
c    4.0
d    5.0
dtype: float64

In [18]:
df = df1+ df2

df

        a    b    c   d
Anjir NaN  NaN  NaN NaN
Anor  NaN  7.0  9.0 NaN
Olma  NaN  1.0  3.0 NaN
Qovun NaN  NaN  NaN NaN
Uzum  NaN  NaN  NaN NaN

In [21]:
df.fill_value = 0
df.mean()   # mar bir ma`lumot turi bo`yicha o`rtacha qiymatni qaytaradi

a    NaN
b    4.0
c    6.0
d    NaN
dtype: float64

In [22]:
df1.apply(np.sum, axis = 1)

Olma     3.0
Anor    12.0
Uzum    21.0
dtype: float64

In [25]:
dff = lambda x: x.max() - x.min()
df.apply(dff)     # shu malumotlarni orasiga apply orqali funksiyamizni qo`qish

a    NaN
b    6.0
c    6.0
d    NaN
dtype: float64

In [29]:
# random qiymatlardan series elementini hosil qilish
obj = pd.Series(np.random.rand(10), index = ['a','b','c','d','e','f','g','h','i','j'])
obj

a    0.590351
b    0.464846
c    0.657363
d    0.112416
e    0.053236
f    0.978567
g    0.153779
h    0.449568
i    0.208428
j    0.759019
dtype: float64

In [35]:
obj.sort_index()   # index ma`lumotlariga ko`ra tartiblash
obj.index.name = 'index'   # ustunga nom berish
obj.head()

index
a    0.590351
b    0.464846
c    0.657363
d    0.112416
e    0.053236
dtype: float64

In [36]:
obj = obj.sort_values()
obj

index
e    0.053236
d    0.112416
g    0.153779
i    0.208428
h    0.449568
b    0.464846
a    0.590351
c    0.657363
j    0.759019
f    0.978567
dtype: float64

In [37]:
# KEling keyingi mashqlar uchun Githubdan kattaroq DF yuklab olamiz
data = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv', index_col=0)
data.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [41]:
data.sort_values(by='price', ascending=False)    # ma`lumotni narx bo`yicha tartiblash

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
502,84900,mercedes-benz,sl-class,2017,clean vehicle,25302,silver,wddjk7ea3hf044968,167607883,florida,usa,2 days left
1340,74000,ford,drw,2019,clean vehicle,10536,no_color,1ft8w4dt6ked32656,167780682,illinois,usa,2 days left
1336,70000,ford,drw,2019,clean vehicle,9643,no_color,1ft8w3dt3kee48276,167780680,illinois,usa,2 days left
277,67000,dodge,challenger,2019,clean vehicle,10944,blue,2c3cdzl97kh518237,167759490,ohio,usa,21 hours left
1215,65500,ford,srw,2019,clean vehicle,6500,black,1ft7w2bt0kec44818,167718954,indiana,usa,21 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...
141,0,dodge,van,2008,salvage insurance,177948,orange,2d8hn44h88r669549,167756157,utah,usa,2 days left
391,0,cadillac,coupe,2000,salvage insurance,105169,white,1g6el12y9yu148063,167651218,virginia,usa,9 days left
285,0,ford,door,2000,salvage insurance,124969,black,1fafp34p7yw270338,167251902,oklahoma,usa,17 hours left
290,0,mazda,door,2009,salvage insurance,117541,gray,jm3er293590215768,167543177,indiana,usa,16 hours left
354,0,ford,pickup,2009,salvage insurance,180364,blue,1ftyr10d19pa60391,167360535,tennessee,usa,2 days left

In [45]:
data.sort_values('mileage', ascending=False)   # ma`lumotlarni avto narxi bo`yicha tartiblash

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
528,1025,peterbilt,truck,2010,salvage insurance,1017936,color:,1xp7d49x0ad793710,167529842,georgia,usa,17 hours left
1827,3200,ford,door,2013,clean vehicle,999999,silver,1fadp3k21dl266148,167727773,south carolina,usa,21 hours left
516,0,peterbilt,truck,2009,salvage insurance,982486,blue,1xp7d49x09d784257,167529788,florida,usa,17 hours left
490,475,peterbilt,truck,2012,salvage insurance,902041,gold,1xp4d49x9cd123630,167529786,florida,usa,17 hours left
531,2000,chevrolet,pickup,2003,clean vehicle,507985,red,1gcgc24u53z128586,167781223,wisconsin,usa,21 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...
1236,4200,ford,door,2013,clean vehicle,0,no_color,1fadp3j23dl155179,167773673,pennsylvania,usa,2 days left
504,100,peterbilt,truck,2012,salvage insurance,0,blue,1xp4d49x1cd144875,167529787,florida,usa,17 hours left
322,0,ford,chassis,1994,salvage insurance,0,green,1fdee14n7rha47894,167359174,california,usa,19 hours left
309,0,chevrolet,door,2004,salvage insurance,0,maroon,3gnek12t74g240524,167418651,wyoming,usa,18 hours left
1619,650,ford,door,2017,salvage insurance,0,black,1fadp3k21hl268441,167651911,california,usa,2 days left