<a href="https://colab.research.google.com/github/bekdata/mohirdev_datascines/blob/main/_030%7C_matplotlib_amalioyt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [59]:
import matplotlib.pyplot as inline
%matplotlib inline

In [ ]:
df = pd.read_html('https://en.tutiempo.net/climate/ws-384570.html')
data = df[0]

In [ ]:
data.shape

(82, 12)

In [ ]:
data.isnull().sum()

Year    0
T       0
TM      0
Tm      0
PP      0
V       0
RA      0
SN      0
TS      0
FG      0
TN      0
GR      0
dtype: int64

In [ ]:
data = tables[3][tables[3].index>1990]

NameError: name 'tables' is not defined

In [44]:
data

         T    TM    Tm PP    V   RA  SN  TS  FG TN GR
Year
1933     -     -     -  -    -    -   -   -   -  -  -
1934     -     -     -  -    -    -   -   -   -  -  -
1935     -     -     -  -    -    -   -   -   -  -  -
1936     -     -     -  -    -    -   -   -   -  -  -
1937     -     -     -  -    -    -   -   -   -  -  -
...    ...   ...   ... ..  ...  ...  ..  ..  .. .. ..
2021    17  23.4  10.1  -   10   82  11  10  14  0  0
2022  16.7  22.6  10.2  -  9.8  115  17  14  32  0  0
2023  17.3  23.6  10.4  -   10   96  15  14  19  0  0
2024     -     -     -  -    -    -   -   -   -  -  -
2025     -     -     -  -    -    -   -   -   -  -  -

[82 rows x 11 columns]

In [47]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 82 entries, 1933 to 2025
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   T       82 non-null     object
 1   TM      82 non-null     object
 2   Tm      82 non-null     object
 3   PP      82 non-null     object
 4   V       82 non-null     object
 5   RA      82 non-null     object
 6   SN      82 non-null     object
 7   TS      82 non-null     object
 8   FG      82 non-null     object
 9   TN      82 non-null     object
 10  GR      82 non-null     object
dtypes: object(11)
memory usage: 7.7+ KB

In [49]:
data.drop().sum()

AttributeError: 'DataFrame' object has no attribute 'dublicated'

In [50]:
data = data.replace('-', np.nan)

In [55]:
data.drop('PP', axis=1, inplace=True)
data.head()

        T   TM   Tm    V   RA   SN   TS   FG   TN   GR
Year
1933  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1934  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1935  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1936  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1937  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [60]:
plt.plot(T)

NameError: name 'plt' is not defined